### PR TITLE
chore: Update Readme

### PR DESCRIPTION
**Pull request by jeromecambon**

### CODE REVIEW

**Comment by uguy** [comment]
Hey guys, 5 days for a PR on a 2 lines changes in a README ?

**Review by uguy — APPROVED** [review]

**Comment by uguy** [comment]
Issue on pr-diff-checker : https://github.com/bonitasoft/actions/issues/112

PR is blocked because the checker does not allow hard link to bonitasoft documentation in README.adoc file.

**Comment by uguy** [comment]
Issue on pr-diff-checker : https://github.com/bonitasoft/actions/issues/112

PR is blocked because the checker does not allow hard link to bonitasoft documentation in README.adoc file.

**Comment by tbouffard** [comment]
You are not blocked to merge the PR (there is no hard requirement about status checks in this repository).
You can ignore the error as it is a false positive in the context of this PR.

**Pull request merged**
